// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo9KF6qwwJaqgSlavhy8mdmNL_o8673eA',
    appId: '1:355779140908:web:822e92041839e9fd246089',
    messagingSenderId: '355779140908',
    projectId: 'expense-calculator-cf615',
    authDomain: 'expense-calculator-cf615.firebaseapp.com',
    storageBucket: 'expense-calculator-cf615.firebasestorage.app',
    measurementId: 'G-X4C26YFNZ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyr6tyBB_kwf7eAglZqOu_-OnAu0Kpnwg',
    appId: '1:355779140908:android:e77b5d5992531d98246089',
    messagingSenderId: '355779140908',
    projectId: 'expense-calculator-cf615',
    storageBucket: 'expense-calculator-cf615.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDryQfCA0eX37umKmX2CL95Ws2shS9WeRo',
    appId: '1:355779140908:ios:dba6879c1e28e986246089',
    messagingSenderId: '355779140908',
    projectId: 'expense-calculator-cf615',
    storageBucket: 'expense-calculator-cf615.firebasestorage.app',
    iosBundleId: 'com.example.simpleExpenseCalculator',
  );
}
